#!/bin/bash
#
# Setup Git Hooks for Observability
#
# This script installs git hooks that automatically update the Redis cache
# when git operations occur (commit, checkout, merge, rebase).
#
# This ensures git context is always up-to-date in Redis without running
# git commands in the critical hook path.
#
# Usage:
#   cd /path/to/your/project
#   ./.claude/scripts/setup_git_hooks.sh
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

HOOKS_DIR=".git/hooks"
SCRIPT_PATH=".claude/hooks/utils/update_git_cache.py"

echo "🔧 Setting up git hooks for observability..."
echo ""

# Check if we're in a git repository
if [ ! -d "$HOOKS_DIR" ]; then
    echo -e "${RED}Error: Not in a git repository (no .git/hooks directory)${NC}"
    echo "Please run this script from the root of your git repository."
    exit 1
fi

# Check if the updater script exists
if [ ! -f "$SCRIPT_PATH" ]; then
    echo -e "${RED}Error: update_git_cache.py not found at $SCRIPT_PATH${NC}"
    echo "Please ensure you're running this from a project with .claude directory."
    exit 1
fi

# Hooks to install
HOOKS=("post-commit" "post-checkout" "post-merge" "post-rebase")

echo "Installing git hooks:"
echo ""

for hook in "${HOOKS[@]}"; do
    hook_path="$HOOKS_DIR/$hook"

    # Backup existing hook if it exists
    if [ -f "$hook_path" ]; then
        echo -e "${YELLOW}  ⚠  Backing up existing $hook to ${hook}.backup${NC}"
        cp "$hook_path" "${hook_path}.backup"
    fi

    # Create new hook
    cat > "$hook_path" << 'EOF'
#!/bin/bash
# Auto-generated by .claude/scripts/setup_git_hooks.sh
# Updates Redis git cache when git operations occur
#
# This hook runs in the background to avoid blocking git operations.
# Errors are logged but don't prevent the git operation from succeeding.

# Run cache update in background (non-blocking)
python .claude/hooks/utils/update_git_cache.py --sync 2>&1 | logger -t git-hook &

# Exit immediately (don't wait for background job)
exit 0
EOF

    chmod +x "$hook_path"
    echo -e "${GREEN}  ✓  Installed $hook${NC}"
done

echo ""
echo -e "${GREEN}✅ Git hooks installed successfully!${NC}"
echo ""
echo "Redis cache will now automatically update on:"
echo "  - git commit"
echo "  - git checkout"
echo "  - git merge"
echo "  - git rebase"
echo ""
echo "This ensures fast (<5ms) hook execution by caching git context."
echo ""
echo "Note: If you're using worktrees, you do not have to run this script in each worktree directory."
